version: '3'
services:
  node-app-1:  # Name of the first Node.js application service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db  # Change 'postgres' to 'db'
      POSTGRES_PORT: 5432
      POSTGRES_DB: Alemeno
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: praveen123
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: Alemeno
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: praveen123


